// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCSBZ3rAr8V60Lbok4S3WCADqMBmD2G_E',
    appId: '1:888897768444:web:7a5ff57a16701026488079',
    messagingSenderId: '888897768444',
    projectId: 'whatchat-707e6',
    authDomain: 'whatchat-707e6.firebaseapp.com',
    storageBucket: 'whatchat-707e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN83_k_5PVPENJxv_M_CM2A-0zSY6rcM4',
    appId: '1:888897768444:android:c23f24e3b48db3a9488079',
    messagingSenderId: '888897768444',
    projectId: 'whatchat-707e6',
    storageBucket: 'whatchat-707e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzC51DB3L1FDGLyuGFju1UtOUNcNMt_Ec',
    appId: '1:888897768444:ios:22dca1d21cf8ceff488079',
    messagingSenderId: '888897768444',
    projectId: 'whatchat-707e6',
    storageBucket: 'whatchat-707e6.appspot.com',
    iosClientId: '888897768444-opqopvl116hvcsoq67mo14chb4t5lvlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzC51DB3L1FDGLyuGFju1UtOUNcNMt_Ec',
    appId: '1:888897768444:ios:22dca1d21cf8ceff488079',
    messagingSenderId: '888897768444',
    projectId: 'whatchat-707e6',
    storageBucket: 'whatchat-707e6.appspot.com',
    iosClientId: '888897768444-opqopvl116hvcsoq67mo14chb4t5lvlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatchat',
  );
}
